### ISSUE TITLE
参数说明

### ISSUE THREAD

**Issue by lzp0070007** [dkzwm/merge_satellite#1]
请问有没有 参数说明呢？

**Comment by dkzwm** [comment]
merge_satellite.py -i 卫星图输入目录 -o 输出目录 -b 经纬度(例如全球：-85.00,180.00,85.00,-180.00) -t 是否支持透明(支持:true,不支持:false) -z 卫星图缩放级别 -d 是否压缩(true/false)>-c 压缩算法 -q 如果是JPEG进行压缩可配置的图像质量
